<?php
// This script is launched before restarting nginx
// to check if a bastard has deleted his directories
// with ftp: nginx would refuse to start otherwise.
$chk_dir_script="#!/bin/sh

echo \"Checking vhosts directories existance...\"\n";
$chk_certs_script = "#!/bin/sh

echo \"Checking certificates validity...\"
EXIT_VAL=0\n";

function pro_nginx_vhost_generate(){
	global $pro_mysql_domain_table;
	global $pro_mysql_admin_table;
	global $pro_mysql_subdomain_table;
	global $pro_mysql_ssl_ips_table;

	global $conf_db_version;
	global $conf_unix_type;

	global $conf_nginx_vhost_path;
	global $conf_generated_file_path;
	global $conf_dtcshared_path;
	global $conf_dtcadmin_path;
	global $conf_dtcclient_path;
	global $conf_dtcdoc_path;
	global $conf_dtcemail_path;
	global $conf_main_site_ip;
	global $conf_use_multiple_ip;
	global $conf_site_addrs;
	global $conf_php_library_path;
	global $conf_php_additional_library_path;
	global $conf_administrative_site;
	global $conf_administrative_ssl_port;
	global $conf_use_ssl;

	global $conf_shared_renewal_shutdown;

	global $conf_use_nated_vhost;
	global $conf_nated_vhost_ip;

	global $console;
	global $chk_dir_script;
	global $chk_certs_script;

	global $conf_main_domain;
	global $conf_404_subdomain;

	global $conf_mysql_db;

	global $conf_nginx_version;
	
	$nginxPort = 8080;
	$conf_administrative_ssl_port = 8081;

	$vhost_file = "";
	$logrotate_file = "# Do not edit this file, it's generated
# edit /etc/dtc/logrotate.template instead!
";

$vhost_file .= "# WARNING ! This file is automatically edited by the dtc cron
# daemon: do not edit. All manual changes to hosts that are configured within
# the dtc panel will be removed with the next cron job. It's the same for all
# files in this folder exept the ssl, the 404 and the template folder.
#
# If you feel an option is missing, feel free to edit the script that generate
# this file in dtc/admin/genfiles/gen_pro_vhosts.php. Best is to send us your
# patch if you feel it's good enough to share.
#
# All non dtc hosts should be added in a SEPARATE file that you should include
# in your httpd.conf or apache.conf See your distribution manual to know where
# to find this file (somewhere in /etc/httpd or /etc/apache2 or even in
# /usr/local/etc/apache/httpd.conf ...).
";

	$vhost_file_listen = "";

	if($conf_unix_type == "gentoo"){
		$conf_tools_prefix = "/var/www/localhost/htdocs";
	}else if($conf_unix_type == "bsd"){
		$conf_tools_prefix = "/usr/local/www";
	}else{
		$conf_tools_prefix = "/usr/share";
	}

	// DB version check
	if(($conf_db_version < 10000 || !isset($conf_db_version)) ||
		!isset($conf_use_ssl) || !isset($conf_use_nated_vhost)){
		$vhost_file .= "# WARNING !!! DATABASE SCHEMA IS COMMING FROM AN HOLD DTC VERSION : PLEASE UPGRADE YOUR TABLES TO NEW VERSION !!!\n";
	}

	$num_generated_vhosts=0;
	$query = "SELECT * FROM $pro_mysql_domain_table WHERE 1 ORDER BY name;";
	$result = mysql_query ($query)or die("Cannot execute query \"$query\"");
	$num_rows = mysql_num_rows($result);

	if($num_rows < 1){
		die("No account to generate : database has to contain AT LEAST one domain name");
	}

	$query2 = "SELECT $pro_mysql_admin_table.path
FROM $pro_mysql_domain_table,$pro_mysql_admin_table
WHERE $pro_mysql_domain_table.name='$conf_main_domain'
AND $pro_mysql_admin_table.adm_login=$pro_mysql_domain_table.owner;";
	$result2 = mysql_query ($query2)or die("Cannot execute query \"$query2\"!");
	$enable404feature = true;
	//echo "Query $query2 resulted in ".mysql_num_rows($result2)."\n";
	if(mysql_num_rows($result2) != 1){
		$enable404feature=false;
	}
	//don't die here... 	we will try and do things to work around this bug
	//die("Cannot find main domain admin path!!!");

	if ($enable404feature == true)
	{
		$a = mysql_fetch_array($result2);
		$path_404 = $a["path"]."/$conf_main_domain/subdomains/$conf_404_subdomain";
		// make sure the vhost_chk_dir script has the 404 entries
                vhost_chk_dir_sh("$path_404/html");
                vhost_chk_dir_sh("$path_404/logs");
                vhost_chk_dir_sh("$path_404/cgi-bin");
	}

	if($conf_use_multiple_ip == "yes" && $conf_use_nated_vhost == "no"){
		$all_site_addrs = explode("|",$conf_site_addrs);
		$nbr_addrs = sizeof($all_site_addrs);
		for($i=0;$i<$nbr_addrs;$i++){
			// first write all config'ed IPs with the Listen
			if (test_valid_local_ip($all_site_addrs[$i]) && !ereg("Listen ".$all_site_addrs[$i].":80", $vhost_file_listen))
			{
				//QH $vhost_file_listen .= "Listen ".$all_site_addrs[$i].":80\n";
			} else {
				//QH $$vhost_file_listen .= "#Listen ".$all_site_addrs[$i].":80\n";
			}
			$query2 = "SELECT * FROM $pro_mysql_domain_table WHERE ip_addr='".$all_site_addrs[$i]."' LIMIT 1;";
			$result2 = mysql_query ($query2)or die("Cannot execute query \"$query\"");
			$num_rows2 = mysql_num_rows($result2);
			if($num_rows2 > 0){
				//QH $vhost_file .= "NameVirtualHost ".$all_site_addrs[$i].":80\n";
				if ($enable404feature == true){
					/* QH $vhost_file .= "<VirtualHost ".$all_site_addrs[$i].":80>
	ServerName $conf_404_subdomain.$conf_main_domain
	DocumentRoot $path_404/html
	ScriptAlias /cgi-bin $path_404/cgi-bin
	ErrorLog $path_404/logs/error.log
	LogSQLTransferLogTable ".str_replace("-","A",str_replace(".","_",$conf_main_domain)).'$'.$conf_404_subdomain.'$'."xfer
	LogSQLScoreDomain $conf_main_domain
	LogSQLScoreSubdomain $conf_404_subdomain
	LogSQLScoreTable $conf_mysql_db.http_accounting
	DirectoryIndex index.php index.cgi index.pl index.htm index.html index.php4
</VirtualHost>\n";
*/
				$vhost_file .= "server {\n\tlisten\t{$all_site_addrs[$i]}:{$nginxPort};
	server_name $conf_404_subdomain.$conf_main_domain;
	location ~ \.php$ {
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $path_404/html\$fastcgi_script_name;
            include        /etc/nginx/fastcgi_params;
        }
	root $path_404/html;
	error_log $path_404/logs/error.log;
	index index.php index.cgi index.pl index.htm index.html index.php4;
}\n\n";
					$logrotate_file .= "$path_404/logs/error.log ";
				}
			}
		}
	}else{
		$ip_for_404=$conf_main_site_ip;
		if($conf_use_nated_vhost=="yes"){
			$ip_for_404 = $conf_nated_vhost_ip;
			if (test_valid_local_ip($conf_nated_vhost_ip) && !ereg("Listen ".$conf_nated_vhost_ip.":80", $vhost_file_listen))
			{
				//QH $vhost_file_listen .= "Listen ".$conf_nated_vhost_ip.":80\n";
			} else {
				//QH $vhost_file_listen .= "#Listen ".$conf_nated_vhost_ip.":80\n";
			}
			//QH $vhost_file .= "NameVirtualHost ".$conf_nated_vhost_ip.":80\n";
		}else{
			if (test_valid_local_ip($conf_main_site_ip) && !ereg("Listen ".$conf_main_site_ip.":80", $vhost_file_listen))
			{
				//QH $vhost_file_listen .= "Listen ".$conf_main_site_ip.":80\n";
			} else {
				//QH $vhost_file_listen .= "#Listen ".$conf_main_site_ip.":80\n";
			}
			//QH $vhost_file .= "NameVirtualHost ".$conf_main_site_ip.":80\n";
		}
		if ($enable404feature == true){
			/* QH $vhost_file .= "<VirtualHost ".$ip_for_404.":80>
        ServerName $conf_404_subdomain.$conf_main_domain
        DocumentRoot $path_404/html
        ScriptAlias /cgi-bin $path_404/cgi-bin
        ErrorLog $path_404/logs/error.log
        LogSQLTransferLogTable ".str_replace("-","A",str_replace(".","_",$conf_main_domain)).'$'.$conf_404_subdomain.'$'."xfer
        LogSQLScoreDomain $conf_main_domain
        LogSQLScoreSubdomain $conf_404_subdomain
        LogSQLScoreTable $conf_mysql_db.http_accounting
        DirectoryIndex index.php index.cgi index.pl index.htm index.html index.php4
</VirtualHost>\n";
*/
			$vhost_file .= "server {\n\tlisten\t{$ip_for_404}:{$nginxPort};
    server_name $conf_404_subdomain.$conf_main_domain;
    location ~ \.php$ {
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $path_404/html\$fastcgi_script_name;
            include        /etc/nginx/fastcgi_params;
        }
    root $path_404/html;
    error_log $path_404/logs/error.log;
    index index.php index.cgi index.pl index.htm index.html index.php4;
};\n\n";
			$logrotate_file .= "$path_404/logs/error.log ";
		}
	}

/* QH
	$vhost_file .= "<Directory $conf_dtcadmin_path>
	Options FollowSymLinks
	Order Deny,Allow
	Allow from all
</Directory>
<Directory $conf_dtcclient_path>
	Options FollowSymLinks
	Order Deny,Allow
	Allow from all
</Directory>
<Directory $conf_dtcemail_path>
	Options FollowSymLinks
	Order Deny,Allow
	Allow from all
</Directory>\n";
*/

//	This is not needed anymore as we don't use cgi-bin for the rrdtool graphing anymore
//	If you need it for your specific config, then add it in the main apache config
//	if($conf_unix_type == "debian"){
//		$vhost_file .= "ScriptAlias /cgi-bin /usr/lib/cgi-bin
//<Directory /usr/lib/cgi-bin>
//	Options FollowSymLinks
//</Directory>\n";
//	}

	for($i=0;$i<$num_rows;$i++){
		$row = mysql_fetch_array($result) or die ("Cannot fetch user");
		$web_name = $row["name"];
		if ($web_name == "")
		{
			print("No name specified for domain, skipping...");
			continue;
		}
		$web_owner = $row["owner"];
		$ip_addr = $row["ip_addr"];
		$domain_safe_mode = $row["safe_mode"];
		$domain_sbox_protect = $row["sbox_protect"];
		$domain_parking = $row["domain_parking"];
		unset($backup_ip_addr);
		if (isset($row["backup_ip_addr"])){
			$backup_ip_addr = $row["backup_ip_addr"];
		}
		if (isset($backup_ip_addr) && ($backup_ip_addr == "NULL" || trim($backup_ip_addr) == "")){
			unset($backup_ip_addr);
		} 
		// need to check if we have a NameVirtualHost entry for this backup IP, to support multiple backup sites on one IP
		if (isset($backup_ip_addr)){
			if (test_valid_local_ip($backup_ip_addr) && !ereg("Listen ".$backup_ip_addr.":80", $vhost_file_listen)){
				//QH $vhost_file_listen .= "Listen ".$backup_ip_addr.":80\n";
			} else {
				//QH $vhost_file_listen .= "#Listen ".$backup_ip_addr.":80\n";
			}
			if (!ereg("NameVirtualHost $backup_ip_addr", $vhost_file)){
				//QH $vhost_file .= "NameVirtualHost ".$backup_ip_addr.":80\n";
			}
		}
		if($conf_use_multiple_ip == "yes"){
			$ip_to_write = $ip_addr;
		}else{
			$ip_to_write = $conf_main_site_ip;
		}
		if($conf_use_nated_vhost == "yes"){
			$ip_to_write = $conf_nated_vhost_ip;
		}
		$web_default_subdomain = $row["default_subdomain"];

		// Get the owner informations
		$query2 = "SELECT * FROM $pro_mysql_admin_table WHERE adm_login='$web_owner';";
		$result2 = mysql_query ($query2)or die("Cannot execute query \"$query2\"");
		$num_rows2 = mysql_num_rows($result2);
		if($num_rows2 != 1){
			die("No user of that name !");
		}
		$webadmin = mysql_fetch_array($result2) or die ("Cannot fetch user");
		$web_path = $webadmin["path"];
		$expire_stored = $webadmin["expire"];
		if($expire_stored == "0000-00-00"){
			$site_expired = "no";
		}else{
			$calc_expire_date = calculateExpirationDate($expire_stored,"0000-00-$conf_shared_renewal_shutdown");
			$calc_expire_date_array = explode("-",$calc_expire_date);
			$expire_timestamp = mktime(1,1,1,$calc_expire_date_array[1],$calc_expire_date_array[2],$calc_expire_date_array[0]);
			if($expire_timestamp < mktime()){
				$site_expired = "yes";
			}else{
				$site_expired = "no";
			}
		}

		if($domain_parking != "no-parking" && $web_name != $conf_main_domain){
			$domain_to_get = $domain_parking;
		}else{
			$domain_to_get = $web_name;
		}

		// Grab all subdomains
		if($web_name == $conf_main_domain){
			$query2 = "SELECT * FROM $pro_mysql_subdomain_table WHERE domain_name='$web_name' AND ip='default' AND subdomain_name!='$conf_404_subdomain' ORDER BY subdomain_name;";
		}else{
			$query2 = "SELECT * FROM $pro_mysql_subdomain_table WHERE domain_name='$domain_to_get' AND ip='default' ORDER BY subdomain_name;";
		}
		$result2 = mysql_query ($query2)or die("Cannot execute query \"$query2\"");
		$num_rows2 = mysql_num_rows($result2);
// This is a bad idea to die in this case
// because it actualy happen if you redirect www ip to something else.
//		if($num_rows2 < 1){
//			die("No subdomain for domain $web_name !");
//		}
		for($j=0;$j<$num_rows2;$j++){
			$subdomain = mysql_fetch_array($result2) or die ("Cannot fetch user");
			$web_subname = $subdomain["subdomain_name"];
			if( $subdomain["customize_vhost"] == ""){
				$custom_directives = "";
			}else{
				$custom_directives = "
	# Start of custom directives
	".$subdomain["customize_vhost"]."
	# End of custom directives";
			}

//			$console .= "Working on $web_subname.$web_name\n";

			// if we explicitly don't want to generate a vhost entry for this subdomain
			if (isset($subdomain["generate_vhost"]) && $subdomain["generate_vhost"] == "no")
			{
				continue;
			}

// ------------------------------------------------
// --- Start of the conf of the panel subdomain ---
// ------------------------------------------------
			if($conf_administrative_site == "$web_subname.$web_name"){
			// generate SSL and non SSL if we have enabled SSL
			$gen_iterations = 1;
			if ($conf_use_ssl == "yes"){
				$gen_iterations++;
			}

			// if we want to generate a backup IP (transitional)
			// need to loop through this one
			if (isset($backup_ip_addr))
			{
				$gen_iterations++;
			}
			for ($k = 0; $k < $gen_iterations; $k++){
				$log_tablename = str_replace("-","A",str_replace(".","_",$web_name)).'$'.str_replace("-","A",str_replace(".","_",$web_subname));
				if($conf_use_ssl == "yes" && $k == 0){
					# add the directive for SSL here
					if (test_valid_local_ip($ip_to_write) && !ereg("Listen ".$ip_to_write.":".$conf_administrative_ssl_port, $vhost_file_listen))
					{
						//QH $vhost_file_listen .= "Listen ".$ip_to_write.":".$conf_administrative_ssl_port."\n";
					} else {
						//QH $vhost_file_listen .= "#Listen ".$ip_to_write.":".$conf_administrative_ssl_port."\n";
					}
					//QH $vhost_file .= "<VirtualHost ".$ip_to_write.":".$conf_administrative_ssl_port.">\n";
					$vhost_file .= "server {\n\tlisten\t{$ip_to_write}:{$conf_administrative_ssl_port};\n";
				} else if ($k == 1 && isset($backup_ip_addr) || ($conf_use_ssl != "yes" && $k == 0 && isset($backup_ip_addr))) {
					//QH $vhost_file .= "<VirtualHost ".$backup_ip_addr.":80>\n";
					$vhost_file .= "server {\n\tlisten\t{$backup_ip_addr}:{$nginxPort};\n";
				}else {
					//QH $vhost_file .= "<VirtualHost ".$ip_to_write.":80>\n";
					$vhost_file .= "server {\n\tlisten\t{$ip_to_write}:{$nginxPort};\n";
				}

				// Added by Luke
				// Needed to create an Alias in httpd.conf for non-resolvable domains
				// This does http://dtc.your-domain.com/unresolved-domain.com
				// TG: added a flag to say yes/no to that alias for each domains
				$alias_domain_query = "SELECT * FROM $pro_mysql_domain_table WHERE gen_unresolved_domain_alias='yes' ORDER BY name;";
				$result_alias = mysql_query ($alias_domain_query)or die("Cannot execute query \"$query\" line ".__LINE__." file ".__FILE__." mysql said: ".mysql_error());
				$num_rows_alias = mysql_num_rows($result_alias);
				for($x=0;$x<$num_rows_alias;$x++) {
					$rowX = mysql_fetch_array($result_alias) or die ("Cannot fetch domain for Alias");
					$web_nameX = $rowX["name"];
					$web_ownerX = $rowX["owner"];
					$ip_addrX = $rowX["ip_addr"];
					$backup_ip_addrX = $rowX["backup_ip_addr"];
					$alias_user_query = "SELECT * FROM $pro_mysql_admin_table WHERE adm_login='$web_ownerX';";
					$alias_user_result = mysql_query($alias_user_query) or die("Cannot fetch user for Alias");
					$num_rows_alias_user = mysql_num_rows($alias_user_result);
					if ($num_rows_alias_user != 1) {
						die("No user of that name!");
					}
					$alias_path = mysql_fetch_array($alias_user_result) or die ("Cannot fetch user");
					$web_pathX = $alias_path["path"];
					// TG: Added open_basedir restriction (for obvious security reasons)
					$qsubdom = "SELECT * FROM $pro_mysql_subdomain_table WHERE domain_name='$web_nameX' AND ip='default';";
					$rx = mysql_query ($qsubdom)or die("Cannot execute query \"$qsubdom\" line ".__LINE__." file ".__FILE__." mysql said: ".mysql_error());
					$numx =  mysql_num_rows($rx);
					for($subx=0;$subx<$numx;$subx++){
						$ax = mysql_fetch_array($rx) or die ("Cannot fetch subdomain for Alias");
						$subdomx = $ax["subdomain_name"];
						$globalx = $ax["register_globals"];
						if($globalx == "yes"){
							$gblx = "php_admin_value register_globals 1";
						}else{
							$gblx = "php_admin_value register_globals 0";
						}
						if($rowX["safe_mode"] == "no" && $ax["safe_mode"] == "no"){
							$safex = "php_admin_value safe_mode 0";
						}else{
							$safex = "php_admin_value safe_mode 1";
						}
						/* QH $vhost_file .= "\tAlias /$subdomx.$web_nameX $web_pathX/$web_nameX/subdomains/$subdomx/html
	<Location /$subdomx.$web_nameX>
		".$safex.$custom_directives."
		php_admin_value open_basedir \"$web_pathX/$web_nameX/:$conf_php_library_path:$conf_php_additional_library_path:\"
		$gblx
	</Location>\n";
*/
						$vhost_file .= "\tlocation /$subdomx.$web_nameX {
		root $web_pathX/$web_nameX/subdomains/$subdomx/html;
	}\n";
					}
				}
				// End of Luke's patch

				//QH $vhost_file .= "	ServerName $web_subname.$web_name\n";
				$vhost_file .= "server_name $web_subname.$web_name;\n";
				if($conf_use_ssl == "yes" && $k == 0){
				$vhost_file .= "        ssl                  on;
        ssl_certificate      ".$conf_generated_file_path."/ssl/new.cert.cert;
        ssl_certificate_key  ".$conf_generated_file_path."/ssl/new.cert.key;
        ssl_session_timeout  5m;
        ssl_protocols  SSLv2 SSLv3 TLSv1;
        ssl_ciphers  ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP;
        ssl_prefer_server_ciphers   on;\n\n";
					/* QH $vhost_file .= "	SSLEngine on
	SSLCertificateFile ".$conf_generated_file_path."/ssl/new.cert.cert
	SSLCertificateKeyFile ".$conf_generated_file_path."/ssl/new.cert.key\n";
*/
/*					$vhost_file .= "\tssl\ton;
	ssl_certificate {$conf_generated_file_path}/ssl/new.cert.cert;
	ssl_certificate_key {$conf_generated_file_path}/ssl/new.cert.key;\n";
*/
				}
				vhost_chk_dir_sh("$web_path/$web_name/subdomains/$web_subname/html");
				vhost_chk_dir_sh("$web_path/$web_name/subdomains/$web_subname/logs");
				vhost_chk_dir_sh("$web_path/$web_name/subdomains/$web_subname/cgi-bin");
/* QH
				$vhost_file .= "	Alias /phpmyadmin ".$conf_tools_prefix."/phpmyadmin
	Alias /dtc $conf_dtcclient_path
	Alias /dtcdoc $conf_dtcdoc_path/html/en
	Alias /dtcemail $conf_dtcemail_path
	Alias /dtcadmin $conf_dtcadmin_path
	Alias /stats $web_path/$web_name/subdomains/$web_subname/logs
	Alias /awstats-icon /usr/share/awstats/icon
	Alias /squirrelmail ".$conf_tools_prefix."/squirrelmail
	Alias /roundcube /var/lib/roundcube
	php_admin_value sendmail_from webmaster@$web_name
	DocumentRoot $web_path/$web_name/subdomains/$web_subname/html
# No ScriptAlias: we want to use system's /usr/lib/cgi-bin !!!
#	ScriptAlias /cgi-bin $web_path/$web_name/subdomains/$web_subname/cgi-bin
	ErrorLog $web_path/$web_name/subdomains/$web_subname/logs/error.log
	LogSQLTransferLogTable $log_tablename\$xfer
	LogSQLScoreDomain $web_name
	LogSQLScoreSubdomain $web_subname
	LogSQLScoreTable $conf_mysql_db.http_accounting
	DirectoryIndex index.php index.cgi index.pl index.htm index.html index.php4$custom_directives
</VirtualHost>

";
*/
				$vhost_file .= "\tlocation /phpmyadmin {
                alias ". $conf_tools_prefix."/phpmyadmin;
        }

        location ~ ^/phpmyadmin.+\.php$ {
                fastcgi_pass   127.0.0.1:9000;
                fastcgi_index  index.php;
                fastcgi_param  SCRIPT_FILENAME  ".$conf_tools_prefix."\$fastcgi_script_name;
                include        /etc/nginx/fastcgi_params;
                fastcgi_param  HTTPS on;
        }
	
	location /dtcemail {
                alias $conf_dtcemail_path;
        }
	location ~ ^/dtcemail(.+\.php)$ {
                fastcgi_pass   127.0.0.1:9000;
                fastcgi_index  index.php;
                fastcgi_param  SCRIPT_FILENAME  ".$conf_dtcemail_path."\$1;
                include        /etc/nginx/fastcgi_params;
                fastcgi_param  HTTPS on;
        }
	location /dtcadmin {
                alias $conf_dtcadmin_path;
        }
	location ~ ^/dtcadmin(.+\.php)$ {
                fastcgi_pass   127.0.0.1:9000;
                fastcgi_index  index.php;
                fastcgi_param  SCRIPT_FILENAME  ".$conf_dtcadmin_path."\$1;
                include        /etc/nginx/fastcgi_params;
                fastcgi_param  HTTPS on;
        }
	location /stats {
                alias $web_path/$web_name/subdomains/$web_subname/logs;
        }
	location ~ ^/stats.+\.php$ {
                fastcgi_pass   127.0.0.1:9000;
                fastcgi_index  index.php;
                fastcgi_param  SCRIPT_FILENAME  $web_path/$web_name/subdomains/$web_subname/logs\$fastcgi_script_name;
                include        /etc/nginx/fastcgi_params;
                fastcgi_param  HTTPS on;
        }
	location /awstats-icon {
                alias /usr/share/awstats/icon;
        }
	location /squirrelmail {
                alias $conf_tools_prefix/squirrelmail;
        }
	location ~ ^/squirrelmail.+\.php$ {
                fastcgi_pass   127.0.0.1:9000;
                fastcgi_index  index.php;
                fastcgi_param  SCRIPT_FILENAME  ".$conf_tools_prefix."/squirrelmail\$fastcgi_script_name;
                include        /etc/nginx/fastcgi_params;
                fastcgi_param  HTTPS on;
        }
	location /roundcube {
                alias /var/lib/roundcube;
        }
	location ~ ^/roundcube.+\.php$ {
                fastcgi_pass   127.0.0.1:9000;
                fastcgi_index  index.php;
                fastcgi_param  SCRIPT_FILENAME  /var/lib/roundcube\$fastcgi_script_name;
                include        /etc/nginx/fastcgi_params;
                fastcgi_param  HTTPS on;
        }
    location /dtc {
        alias $conf_dtcclient_path;
    }
        location ~ ^/dtc(.+\.php)$ {
                fastcgi_pass   127.0.0.1:9000;
                fastcgi_index  index.php;
                fastcgi_param  SCRIPT_FILENAME  ".$conf_dtcclient_path."\$1;
                include        /etc/nginx/fastcgi_params;
                fastcgi_param  HTTPS on;
        }
    location /dtcdoc {
                alias $conf_dtcdoc_path/html/en;
        }
	root $web_path/$web_name/subdomains/$web_subname/html;
	location ~ \.php$ {
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $web_path/$web_name/subdomains/$web_subname/html/\$fastcgi_script_name;
            include        /etc/nginx/fastcgi_params;
        }
	index index.php index.cgi index.pl index.htm index.html index.php4;
}\n\n";
	
			$logrotate_file .= "$web_path/$web_name/subdomains/$web_subname/logs/error.log ";
} // - end of for loop

// ---------------------------------------------------
// --- Start of the conf of server users subdomain ---
// ---------------------------------------------------
			} else {
				// Generate a permanet redirect for all subdomains of target if using a domain parking
				if($domain_parking != "no-parking"){
					if($j == 0){
						$console .= "Making domain parking for $web_name\n";
						/* QH $vhost_file .= "<VirtualHost ".$ip_to_write.":80>
	ServerName $web_name
	Redirect permanent / http://$domain_parking/
</VirtualHost>\n\n";
*/
						$vhost_file .= "server {\n\tlisten\t{$ip_to_write}:{$nginxPort};
	server_name $web_name;
	rewrite ^(.*)$ http://{$domain_parking}/ permanent;
}\n\n";
					}
					$console .= "Making domain parking for $web_subname.$web_name\n";
/* QH
					$vhost_file .= "<VirtualHost ".$ip_to_write.":80>
	ServerName $web_subname.$web_name
	Redirect permanent / http://$web_subname.$domain_parking/
</VirtualHost>\n\n";
*/
					$vhost_file .= "server {\n\tlisten\t{$ip_to_write}:{$nginxPort};
        server_name $web_subname.$web_name;
        rewrite ^(.*)$ http://{$web_subname}.{$domain_parking}/ permanent;
}\n\n";
				}else{
					vhost_chk_dir_sh("$web_path/$web_name/subdomains/$web_subname/logs");
					vhost_chk_dir_sh("$web_path/$web_name/subdomains/$web_subname/html");
					vhost_chk_dir_sh("$web_path/$web_name/subdomains/$web_subname/cgi-bin");
					$iteration_table = array();
					$iteration_table[] = "normal";
					$ssl_cert_folder_path = "$web_path/$web_name/subdomains/$web_subname/ssl";
					if($subdomain["ssl_ip"] != "none"){
						$ssl_returns = checkCertificate($ssl_cert_folder_path,$web_subname.".".$web_name);
						if($ssl_returns == "yes"){
							$iteration_table[] = "ssl";
							// Start of <krystian@ezpear.com> patch
							if($conf_use_nated_vhost=="yes"){
								$q="select port from $pro_mysql_ssl_ips_table where ip_addr='${subdomain["ssl_ip"]}' and available='no';";
								$r=mysql_query($q)or die("Cannot query \"$q\" line ".__LINE__." file ".__FILE__." sql said: ".mysql_error());
								$n = mysql_num_rows($r);
								if($n > 0){
									$row=mysql_fetch_array($r);
									$port=$row["port"];
									$ip_vhost=$ip_to_write;
									if(empty($port)){
										$port = $nginxSSLPort;
									}
								}else{
									$port = $nginxSSLPort;
									$ip_vhost = $subdomain["ssl_ip"];
								 }
							}else{
								$port = $nginxSSLPort;
							}
							// End of <krystian@ezpear.com> patch
						}
					}

					// if we want to generate a backup IP (transitional)
					// need to loop through this one
					if (isset($backup_ip_addr)){
						$iteration_table[] = "backup";
					}

					$log_tablename = str_replace("-","A",str_replace(".","_",$web_name)).'$'.str_replace("-","A",str_replace(".","_",$web_subname));
					$vhost_more_conf = "";
					$vhost_additional_server_name = "";
					if($subdomain["register_globals"] == "yes"){
						//QH $vhost_more_conf .= "	php_admin_value register_globals 1\n";
					}
					if($web_subname == "$web_default_subdomain"){
						//QH $vhost_more_conf .= "	ServerAlias $web_name\n";
						$vhost_additional_server_name .= "$web_name"; 
					}

					// Sbox and safe mode protection values
					if($domain_safe_mode == "no" && $subdomain["safe_mode"] == "no"){
						$safe_mode_value = "0";
					}else{
						$safe_mode_value = "1";
					}
					if($domain_sbox_protect == "no" && $subdomain["sbox_protect"] == "no"){
						$cgi_directive = "ScriptAlias /cgi-bin $web_path/$web_name/subdomains/$web_subname/cgi-bin";
					}else{
						$cgi_directive = "RewriteEngine on
	RewriteRule ^/cgi-bin/(.*) /cgi-bin/sbox/$1 [PT]";
					}
					$gen_iterations = sizeof($iteration_table);
					for ($k = 0; $k < $gen_iterations; $k++){
						switch($iteration_table[$k]){
						case "backup":
							//QH $vhost_file .= "<VirtualHost ".$backup_ip_addr.":80>\n";
							$vhost_file .= "server {\n\tlisten\t{$backup_ip_addr}:{$nginxPort};\n";
							break;
						case "normal":
							//QH $vhost_file .= "<VirtualHost ".$ip_to_write.":80>\n";
							$vhost_file .= "server {\n\tlisten\t{$ip_to_write}:{$nginxPort};\n";
							break;
						case "ssl":
							//if($conf_use_nated_vhost=="no"){
							//	$vhost_file .= "Listen ".$ip_vhost.":$port\n";
							//}
/* QH
							$vhost_file .= "Listen ".$subdomain["ssl_ip"].":$port\n";
							$vhost_file .= "<VirtualHost ".$subdomain["ssl_ip"].":$port>\n";
							$vhost_file .= "	SSLEngine on\n";
							$vhost_file .= "	SSLCertificateFile $ssl_cert_folder_path/".$web_subname.".".$web_name.".cert.cert\n";
							$vhost_file .= "	SSLCertificateKeyFile $ssl_cert_folder_path/".$web_subname.".".$web_name.".cert.key\n";
*/
							$vhost_file .= "server {\n\tlisten {$subdomain["ssl_ip"]}:{$port};\n";
/*
	ssl\ton
	ssl_certificate {$ssl_cert_folder_path}/{$web_subname}.{$web_name}.cert.cert;
	ssl_certificate_key {$ssl_cert_folder_path}/{$web_subname}.{$web_name}.cert.key;\n";
*/

							break;
						}
/* QH
						$vhost_file .= "	ServerName $web_subname.$web_name
	Alias /stats $web_path/$web_name/subdomains/$web_subname/logs
	Alias /awstats-icon /usr/share/awstats/icon\n";
*/
						$vhost_file .= "\tserver_name $web_subname.$web_name $vhost_additional_server_name;
	location /stats {
		root $web_path/$web_name/subdomains/$web_subname/logs;
	}

	location /awstats-icon {
		root /usr/share/awstats/icon;
	}\n\n";


						// Disable the site if expired
						if($site_expired == "yes"){
							$document_root = $conf_generated_file_path."/expired_site";
							//QH $vhost_file .= "	DocumentRoot $document_root\n";
							$vhost_file .= "\troot $document_root;\n";
						}else{
							$document_root = "$web_path/$web_name/subdomains/$web_subname/html";
							/* QH $vhost_file .= "	DocumentRoot $document_root
$vhost_more_conf	php_admin_value safe_mode $safe_mode_value
	php_admin_value sendmail_from webmaster@$web_name
	php_value session.save_path $web_path/$web_name/subdomains/$web_subname/tmp
	<Location />
		php_admin_value open_basedir \"$web_path:$conf_php_library_path:$conf_php_additional_library_path:\"
	</Location>
	$cgi_directive\n".get_defaultCharsetDirective($subdomain["add_default_charset"]);
*/
							$vhost_file .= "\t root $document_root;\n";
						}
/* QH
						$vhost_file .= "	ErrorLog $web_path/$web_name/subdomains/$web_subname/logs/error.log
	LogSQLTransferLogTable $log_tablename\$xfer
	LogSQLScoreDomain $web_name
	LogSQLScoreSubdomain $web_subname
	LogSQLScoreTable $conf_mysql_db.http_accounting
	DirectoryIndex index.php index.cgi index.pl index.htm index.html index.php4$custom_directives
</VirtualHost>

";
*/
						$vhost_file .= "\terror_log $web_path/$web_name/subdomains/$web_subname/logs/error.log;
	location ~ \.php$ {
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $document_root\$fastcgi_script_name;
            include        /etc/nginx/fastcgi_params;
        }
	index index.php index.cgi index.pl index.htm index.html index.php4;
}\n\n";
						$logrotate_file .= "$web_path/$web_name/subdomains/$web_subname/logs/error.log ";
						$num_generated_vhosts += $num_rows2;
					}
				}
			}
	        }
	}

	// Writting the vhosts.conf file
	//QH
	$conf_nginx_vhost_path = "nginx/vhosts.conf";
	$filep = fopen("$conf_generated_file_path/$conf_nginx_vhost_path", "w+");
	if( $filep == NULL){
		die("Cannot open $conf_generated_file_path/$conf_nginx_vhost_path file for writting");
	}
//QH	fwrite($filep,$vhost_file_listen);
	fwrite($filep,$vhost_file);
	fclose($filep);
	$console .= "$num_generated_vhosts nginx vhosts generated !<br>";

	// Writting the vhost_check_dir script
	$filep = fopen("$conf_generated_file_path/vhost_check_dir","w+");
	if( $filep == NULL){
		echo("Cannot open $conf_generated_file_path/vhost_check_dir file for writting");
	}else{
		fwrite($filep,$chk_dir_script);
		fclose($filep);
	}
	$console .= "vhost_check_dir.sh script written !<br>";

	// Writing the vhost_check_ssl_cert script
	$chk_certs_script .= "exit \$EXIT_VAL";
	$filep = fopen("$conf_generated_file_path/vhost_check_ssl_cert","w+");
	if( $filep == NULL){
		echo("Cannot open $conf_generated_file_path/vhost_check_ssl_cert file for writting");
	}else{
		fwrite($filep,$chk_certs_script);
		fclose($filep);
		chmod("$conf_generated_file_path/vhost_check_ssl_cert",0700);
	}
	$console .= "vhost_check_ssl_cert script written !<br>";

	// Writing the logrotate configuration file
	if($logrotate_file != ""){
			$fname = "";
			if( file_exists("/etc/dtc/logrotate.template") ){
				$fname = "/etc/dtc/logrotate.template";
			}else if( file_exists("/usr/local/etc/dtc/logrotate.template") ){
				$fname = "/usr/local/etc/dtc/logrotate.template";
			}
			if($fname != ""){
				$fp = fopen($fname,"r");
				if($fp != NULL){
					$logrotate_template = fread($fp,filesize($fname));
					fclose($fp);
				}else{
					$logrotate_template = "";
				}
			}else{
					$logrotate_template = "";
			}
			$logrotate_file .= " {
$logrotate_template

	sharedscripts
";
    	$logrotate_file .= "
	postrotate
		if [ -f /var/run/nginx.pid ]; then
			/etc/init.d/nginx restart > /dev/null
		fi
	endscript
}
";
/*QH 
		$filep = fopen("$conf_generated_file_path/logrotate","w+");
		if( $filep == NULL){
			echo ("Cannot open $conf_generated_file_path/logrotate for writting");
		}else{
			fwrite($filep,$logrotate_file);
			fclose($filep);
		}
*/
		$console .= "logrotate config file generated!<br>";
	}
	return true;
}

?>
